Debug Query as SQL string.
ClickHouse/clickhouse-rs pull request #155
Opened 2024-09-18 20:58 UTC by pravic

## Summary

Allow to print the current SQL query, whether it's bound or not. Useful for logging and diagnostics.

closes #146 

## Checklist
Delete items not relevant to your PR:
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided so that we can include it in CHANGELOG later
- [ ] For significant changes, documentation in README and https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials
- [ ] **conflicts** with #154, this PR needs to be rebased on top of that

2024-09-19 13:25 UTC, serprex approved these changes

2024-09-20 16:26 UTC, loyd requested changes
Only misleading `Debug` impl, all other changes are fine

2024-09-20 18:52 UTC, pravic commented on src/query.rs
> +        write!(f, "{sql}", sql = self.sql)
Also, `sql_display` or `as_sql`?

2024-09-20 18:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-rs?pullRequest=155) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-rs?pullRequest=155) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pravic<br/>:x: nxyury<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-rs?pullRequest=155) it.</sub>

2024-09-20 18:55 UTC, pravic commented on src/query.rs
> +        write!(f, "{sql}", sql = self.sql)
@loyd Removed `Debug` in f4da92b.

2024-09-24 07:21 UTC, loyd approved these changes

2024-09-24 07:23 UTC, merged

2024-09-24 07:23 UTC, loyd commented
@pravic, thanks for your contribution!