Exposed method to control the `readonly` query parameter
ClickHouse/clickhouse-rs pull request #181
Opened 2024-11-25 23:56 UTC by serg-temchenko

## Summary

This PR is meant to improve the control over the readonly option sent by the client to the CH database. Right now, it is defined by some methods like [`Query::do_execute`](https://github.com/ClickHouse/clickhouse-rs/blob/main/src/query.rs#L135C19-L135C29), but most of the public methods like Query::fetch, [`Query::fetch_one`](https://github.com/ClickHouse/clickhouse-rs/blob/main/src/query.rs#L96C18-L96C27), or [`Query::fetch_all`](https://github.com/ClickHouse/clickhouse-rs/blob/main/src/query.rs#L121C18-L121C27) don’t have control over this option. This makes it impossible to query the database with queries that contain a lot of columns and require temporary table creation on the database side, which results in the following error:

> Code: 164. DB::Exception: db_user: Cannot execute query in readonly mode. (READONLY) (version 24.10.1.2812 (official build))

By adding the changes in this PR, we will gain control over this option, making it possible to request data that requires the creation of temporary tables by CH.

## Checklist
- [ ] A human-readable description of the changes was provided so that we can include it in CHANGELOG later

2024-11-25 23:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-rs?pullRequest=181) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-rs?pullRequest=181) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-rs?pullRequest=181) it.</sub>

2024-11-26 12:22 UTC, slvrtrn commented on src/query.rs
> +        self.do_execute()?.finish().await
As it is now set as `true` by default, won't this fail with DDLs now?

2024-11-26 12:26 UTC, slvrtrn requested changes
Thanks for the contribution; it makes sense, given that the `read-only` param is hardcoded by default. Let's fix the logic (see the comment, CI also confirms that), add some more tests regarding enabled/disabled `readonly` mode, and maybe an example illustrating the use case.

NB: failing MSRV CI check is supposed to be fixed after https://github.com/ClickHouse/clickhouse-rs/pull/180

2024-11-27 14:32 UTC, slvrtrn commented
CC @loyd @serprex have a look please ^

2024-11-28 04:33 UTC, serg-temchenko commented
Hey @slvrtrn. Sure, I can check/extend tests and docs. But I’m just thinking if overwriting with 0 is the proper way to go, I mean including the `readonly` option all the time, since afaik it can be configured on the DB side. Basically, the user can be configured with the required access level. It will just limit the client and require handling that on both sides, which is a bit redundant and needs additional maintenance. But, as long as I can perform `SELECT` queries without encountering confusing exceptions, I'm okay with that :)

> would it make more sense just to make it so that .with_option("readonly," "0") overrides the default hardcoded read-only param?

Based on [this](https://github.com/ClickHouse/clickhouse-rs/blob/main/src/query.rs#L147-L152) code with hardcoded flag and [this](https://github.com/ClickHouse/clickhouse-rs/pull/176) PR, I assume it will not overwrite it by default if it is already present in the options.

2024-12-03 22:49 UTC, slvrtrn commented
Perhaps we can just remove `readonly` setting, which is enforced by default; IIRC, no other language client does that. Maybe this approach will be even more flexible (`readonly` can still be attached using `with_option`) https://github.com/ClickHouse/clickhouse-rs/pull/184

2024-12-10 18:39 UTC, serg-temchenko commented
Sure, this will work as well. Thanks.

2025-06-09 11:13 UTC, slvrtrn commented
Closing it for now. Let's discuss it in: https://github.com/ClickHouse/clickhouse-rs/issues/230

2025-06-09 11:13 UTC, closed without merging