Chrono support
ClickHouse/clickhouse-rs pull request #188
Opened 2024-12-11 09:16 UTC by dean-shaff

## Summary
Add support for [chrono](https://docs.rs/chrono/latest/chrono/). 

## Checklist
Delete items not relevant to your PR:
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided so that we can include it in CHANGELOG later
- [x] For significant changes, documentation in README and https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

2024-12-11 09:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-rs?pullRequest=188) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-rs?pullRequest=188) before we can accept your contribution.<br/><hr/>**Dean Shaff** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-rs?pullRequest=188) it.</sub>

2024-12-11 15:39 UTC, serprex submitted a review, later dismissed

2024-12-12 13:29 UTC, serprex submitted a review, later dismissed

2024-12-12 14:14 UTC, serprex commented
https://strawlab.org/strand-braid-api-docs/latest/chrono/naive/serde/ts_microseconds/index.html should give microsecond precision, fixing CI

2024-12-16 08:34 UTC, loyd requested changes
Thanks for your contribution!

2024-12-16 08:34 UTC, loyd commented on Cargo.toml
> +chrono = ["dep:chrono", "dep:serde_json"]
It shouldn't require the `serde_json` crate.

2024-12-16 08:34 UTC, loyd commented on README.md
> +        ts: u32,
`ts` and `dt` are shown in one `struct MyRow,` so let's show `chrono` also in that one row; it seems redundant to copy-paste the `ts` variant here.

Same for other examples

2024-12-16 08:34 UTC, loyd commented on README.md
> +* `Date32` maps to/from `i32` or a newtype around it and represents a number of days elapsed since `1970-01-01`. Also, [`time::Date`](https://docs.rs/time/latest/time/struct.Date.html) is supported b
Let's rephrase it using a list with all variants.

Also, to be consistent, we need to provide a link to these types (as for time-based types).

2024-12-16 08:34 UTC, loyd commented on examples/data_types_derive_simple.rs
> +
What about adding the `time_` prefix to the lines above?

2024-12-16 08:34 UTC, loyd commented on src/serde.rs
> +#[cfg(feature = "chrono")]
This logic should be tested in the same way as the `time` feature (via integration tests with a real CH server without `serde_json`)
https://github.com/ClickHouse/clickhouse-rs/blob/main/tests/it/time.rs

This unit tests are useless with more reliable integration tests.

2024-12-16 08:34 UTC, loyd commented on src/serde.rs
> +                    S::Error::custom(format!("Can't create a timestamp from {dt}"))
These messages aren't consistent with `time` variants

2025-01-08 11:55 UTC, dean-shaff commented on src/serde.rs
> +                    S::Error::custom(format!("Can't create a timestamp from {dt}"))
I think I've resolved this with latest commits

2025-01-08 11:55 UTC, dean-shaff commented on examples/data_types_derive_simple.rs
> +
done!

2025-01-08 11:55 UTC, dean-shaff commented on README.md
> +* `Date32` maps to/from `i32` or a newtype around it and represents a number of days elapsed since `1970-01-01`. Also, [`time::Date`](https://docs.rs/time/latest/time/struct.Date.html) is supported b
Let me know if the way I've reformatted this works!

2025-01-08 14:01 UTC, serprex approved these changes

2025-01-08 14:02 UTC, serprex submitted a review, later dismissed

2025-01-16 17:35 UTC, slvrtrn commented
@dean-shaff, can you please sign the CLA? We won't be able to merge without it.

2025-01-19 10:56 UTC, loyd commented on README.md
> +        days: u16,
It's unrelated to `chrono` in any way; let's merge it all into `MyRow` in the same way as it's shown for `DateTime64`.

2025-01-19 18:38 UTC, StashOfCode commented
When is this getting released?

2025-01-20 04:25 UTC, StashOfCode commented
Hey, if you add a mod with `DateTime::<Utc>::from_str`, some types of datetime strings would become insertable into Clickhouse, e.g. `2025-01-19 16:36:15.157350+00:00`.
See https://docs.rs/chrono/latest/src/chrono/datetime/mod.rs.html#1816-1818

```rust
pub mod dt_from_str {
    use super::*;

    // type DateTimeUtc = DateTime<Utc>;

    // option!(
    //     DateTimeUtc,
    //     "Ser/de `Option<DateTime<Utc>>` to/from `Nullable(DateTime)`."
    // );

    pub fn serialize<S>(dt: &DateTime<Utc>, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let ts: i64 = dt.timestamp();

        u32::try_from(ts)
            .map_err(|_| S::Error::custom(format!("{dt} cannot be represented as DateTime")))?
            .serialize(serializer)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<DateTime<Utc>, D::Error>
    where
        D: Deserializer<'de>,
    {
        let ts: String = Deserialize::deserialize(deserializer)?;
        DateTime::<Utc>::from_str(&ts).map_err(|_| {
            D::Error::custom(format!("{ts} cannot be converted to DateTime<Utc>"))
        })
    }


#[derive(Serialize, Deserialize, Debug, Row)]
pub struct MyRow {
    pub id: String,
    #[serde(with = "dt_from_str")]
    pub requested_at: DateTime<Utc>,
```

2025-01-20 15:39 UTC, dean-shaff commented
Hi, I'm not sure why but I'm not able to sign the CLA; have others had issues with this in the past?

2025-01-20 15:48 UTC, dean-shaff commented on README.md
> +        days: u16,
Should be done now!

2025-01-20 17:07 UTC, serprex approved these changes

2025-01-20 19:56 UTC, slvrtrn approved these changes

2025-01-20 19:58 UTC, slvrtrn commented
@loyd

> Merging is blocked
> Merging can be performed automatically once the requested changes are addressed.

If everything is OK with this PR, let's merge and release it with the current pending changes as 0.14.0?

2025-01-22 08:45 UTC, loyd approved these changes

2025-01-22 08:45 UTC, loyd commented
LGTM, let's merge

2025-01-22 10:43 UTC, StashOfCode commented
@dean-shaff, I found a crate called `serde_with` that seems to have already implemented what I did for myself. The documentation is pretty bad there though :/

2025-01-22 12:30 UTC, merged